url: "https://coviditalia.info" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "SnoozleStudio" # the name of your site, e.g. ACME Corp.
lang: "it"

sass:
  sass_dir: _sass

exclude:
 - Makefile
 - package.json
 - yarn.lock